package main_test

import (
	"strings"
	"testing"

	main "github.com/lcox74/aoc25/day07"
	"github.com/stretchr/testify/require"
)

// exampleInput is the sample input from the problem description.
const exampleInput = `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`

func TestExample(t *testing.T) {
	solver := main.NewTachyonManifold()
	solver.Parse(strings.NewReader(exampleInput))

	// Part 1: beam is split 21 times
	require.Equal(t, 21, solver.ResultPart1)

	// Part 2: particle ends up on 40 different timelines
	require.Equal(t, 40, solver.ResultPart2)
}
